export type TopicNode = {
  id: string;
  label: string;
  description?: string;
  kind: "group" | "leaf";
  children?: TopicNode[];
};

export const POLL_TOPICS: TopicNode[] = [
  {
    id: "all",
    label: "All polls",
    description: "Browse every active poll across vehicles, pricing, ADA, cities, and events with pagination.",
    kind: "leaf",
  },
  {
    id: "vehicles",
    label: "Vehicles polls",
    description: "Party buses vs limos vs sedans vs coaches – how riders actually choose their ride.",
    kind: "group",
    children: [
      { id: "party-bus", label: "Party buses", kind: "leaf" },
      { id: "limos", label: "Limousines", kind: "leaf" },
      { id: "coach-bus", label: "Coach buses", kind: "leaf" },
    ],
  },
  {
    id: "pricing",
    label: "Pricing polls",
    description: "Hourly vs flat rates, add-on fees, discounts, deposits, and how people feel about pricing.",
    kind: "group",
    children: [
      { id: "pricing", label: "General pricing", kind: "leaf" },
      { id: "fees", label: "Fees & surcharges", kind: "leaf" },
      { id: "tips", label: "Tips & driver gratuity", kind: "leaf" },
      { id: "discounts", label: "Discounts & promos", kind: "leaf" },
      { id: "refunds", label: "Refunds & cancellations", kind: "leaf" },
    ],
  },
  {
    id: "ada",
    label: "ADA & accessibility polls",
    description: "Wheelchair ramps and lifts, service animals, and accessibility expectations by riders.",
    kind: "group",
    children: [
      { id: "ada", label: "Accessibility (general)", kind: "leaf" },
      { id: "wheelchair", label: "Wheelchair ramps & lifts", kind: "leaf" },
      { id: "service-animal", label: "Service animals", kind: "leaf" },
      { id: "mobility", label: "Mobility comfort", kind: "leaf" },
    ],
  },
  {
    id: "regions",
    label: "Regions & states polls",
    description: "Southwest vs West Coast vs Midwest vs Northeast – different expectations by region.",
    kind: "group",
    children: [
      {
        id: "region-west-coast",
        label: "West Coast",
        description: "California, Oregon, and Washington riders",
        kind: "group",
        children: [
          {
            id: "region-west-coast-ca",
            label: "California",
            description: "Choose a major city in CA",
            kind: "group",
            children: [
              { id: "city-los-angeles", label: "Los Angeles", kind: "leaf" },
              { id: "city-san-diego", label: "San Diego", kind: "leaf" },
              { id: "city-san-francisco", label: "San Francisco", kind: "leaf" },
            ],
          },
          {
            id: "region-west-coast-wa-or",
            label: "Washington & Oregon",
            description: "Pick a flagship city",
            kind: "group",
            children: [
              { id: "city-seattle", label: "Seattle", kind: "leaf" },
              { id: "city-portland", label: "Portland", kind: "leaf" },
            ],
          },
          {
            id: "region-west-coast-major-metros",
            label: "West Coast metros",
            description: "Los Angeles, San Francisco, Seattle",
            kind: "leaf",
          },
        ],
      },
      {
        id: "region-southwest",
        label: "Southwest",
        description: "Arizona, New Mexico, Texas, Nevada",
        kind: "group",
        children: [
          {
            id: "state-az",
            label: "Arizona",
            kind: "group",
            children: [
              { id: "city-phoenix", label: "Phoenix", kind: "leaf" },
              { id: "city-tucson", label: "Tucson", kind: "leaf" },
              { id: "city-tempe", label: "Tempe", kind: "leaf" },
            ],
          },
          {
            id: "state-tx",
            label: "Texas",
            kind: "group",
            children: [
              { id: "city-dallas", label: "Dallas", kind: "leaf" },
              { id: "city-austin", label: "Austin", kind: "leaf" },
              { id: "city-houston", label: "Houston", kind: "leaf" },
              { id: "city-san-antonio", label: "San Antonio", kind: "leaf" },
            ],
          },
          {
            id: "state-nm",
            label: "New Mexico",
            kind: "group",
            children: [
              { id: "city-albuquerque", label: "Albuquerque", kind: "leaf" },
              { id: "city-santa-fe", label: "Santa Fe", kind: "leaf" },
            ],
          },
          {
            id: "state-nv",
            label: "Nevada",
            kind: "group",
            children: [
              { id: "city-las-vegas", label: "Las Vegas", kind: "leaf" },
              { id: "city-reno", label: "Reno", kind: "leaf" },
            ],
          },
        ],
      },
      {
        id: "major-metros",
        label: "Major Metros",
        description: "Top demand hubs coast to coast",
        kind: "group",
        children: [
          { id: "city-new-york", label: "New York City", kind: "leaf" },
          { id: "city-los-angeles", label: "Los Angeles", kind: "leaf" },
          { id: "city-chicago", label: "Chicago", kind: "leaf" },
          { id: "city-houston", label: "Houston", kind: "leaf" },
          { id: "city-phoenix", label: "Phoenix", kind: "leaf" },
          { id: "city-philadelphia", label: "Philadelphia", kind: "leaf" },
          { id: "city-san-antonio", label: "San Antonio", kind: "leaf" },
          { id: "city-san-diego", label: "San Diego", kind: "leaf" },
          { id: "city-dallas", label: "Dallas", kind: "leaf" },
          { id: "city-austin", label: "Austin", kind: "leaf" },
          { id: "city-denver", label: "Denver", kind: "leaf" },
          { id: "city-las-vegas", label: "Las Vegas", kind: "leaf" },
          { id: "city-miami", label: "Miami", kind: "leaf" },
          { id: "city-orlando", label: "Orlando", kind: "leaf" },
          { id: "city-atlanta", label: "Atlanta", kind: "leaf" },
          { id: "city-seattle", label: "Seattle", kind: "leaf" },
          { id: "city-san-francisco", label: "San Francisco", kind: "leaf" },
          { id: "city-san-jose", label: "San Jose", kind: "leaf" },
          { id: "city-boston", label: "Boston", kind: "leaf" },
          { id: "city-washington-dc", label: "Washington, DC", kind: "leaf" },
        ],
      },
      {
        id: "suburbs",
        label: "Suburbs",
        description: "High-income outskirts & commuter towns",
        kind: "group",
        children: [
          { id: "city-naperville", label: "Naperville, IL", kind: "leaf" },
          { id: "city-irvine", label: "Irvine, CA", kind: "leaf" },
          { id: "city-scottsdale", label: "Scottsdale, AZ", kind: "leaf" },
        ],
      },
      {
        id: "region-midwest",
        label: "Midwest",
        description: "Great Lakes and plains riders",
        kind: "group",
        children: [
          {
            id: "state-il",
            label: "Illinois",
            description: "Chicago + statewide metros",
            kind: "group",
            children: [
              { id: "city-chicago", label: "Chicago", kind: "leaf" },
              { id: "city-aurora", label: "Aurora", kind: "leaf" },
              { id: "city-joliet", label: "Joliet", kind: "leaf" },
              { id: "city-naperville", label: "Naperville", kind: "leaf" },
              { id: "city-arlington-heights", label: "Arlington Heights", kind: "leaf" },
              { id: "city-berwyn", label: "Berwyn", kind: "leaf" },
              { id: "city-bloomington", label: "Bloomington", kind: "leaf" },
              { id: "city-bolingbrook", label: "Bolingbrook", kind: "leaf" },
              { id: "city-capital", label: "Springfield / Capital", kind: "leaf" },
              { id: "city-champaign", label: "Champaign", kind: "leaf" },
              { id: "city-cicero", label: "Cicero", kind: "leaf" },
              { id: "city-des-plaines", label: "Des Plaines", kind: "leaf" },
              { id: "city-elgin", label: "Elgin", kind: "leaf" },
              { id: "city-evanston", label: "Evanston", kind: "leaf" },
              { id: "city-hoffman-estates", label: "Hoffman Estates", kind: "leaf" },
              { id: "city-leyden", label: "Leyden", kind: "leaf" },
            ],
          },
        ],
      },
      { id: "region-west", label: "Western US", kind: "leaf" },
      { id: "region-northeast", label: "Northeast", kind: "leaf" },
      { id: "region-southeast", label: "Southeast", kind: "leaf" },
    ],
  },
  {
    id: "cities",
    label: "City & metro polls",
    description: "Big-city vs suburb expectations, pick-up windows, traffic tolerance, and late-night rules.",
    kind: "group",
    children: [
      { id: "city-major", label: "Major metros", kind: "leaf" },
      { id: "city-suburbs", label: "Suburbs", kind: "leaf" },
      { id: "city-rural", label: "Rural / out-of-town", kind: "leaf" },
    ],
  },
  {
    id: "events",
    label: "Events & occasions polls",
    description: "Prom, weddings, concerts, haunted houses, holiday lights, wine tours, brewery crawls.",
    kind: "group",
    children: [
      { id: "prom", label: "Prom & school events", kind: "leaf" },
      { id: "wedding", label: "Weddings", kind: "leaf" },
      { id: "concert", label: "Concerts & festivals", kind: "leaf" },
      { id: "haunted-house", label: "Haunted houses", kind: "leaf" },
      { id: "holiday-lights", label: "Holiday lights", kind: "leaf" },
      { id: "wine-tour", label: "Wine tours", kind: "leaf" },
      { id: "brewery-tour", label: "Brewery tours", kind: "leaf" },
      { id: "night-out", label: "Night out", kind: "leaf" },
    ],
  },
  {
    id: "rules",
    label: "BYOB, rules & comfort polls",
    description: "BYOB, bathroom stops, music control, smoking/vaping, climate, and comfort preferences.",
    kind: "group",
    children: [
      { id: "byob", label: "BYOB & alcohol", kind: "leaf" },
      { id: "rules", label: "Rules & policies", kind: "leaf" },
      { id: "comfort", label: "Comfort & seating", kind: "leaf" },
      { id: "music-playlists", label: "Music & playlists", kind: "leaf" },
      { id: "smoking", label: "Smoking & vaping", kind: "leaf" },
    ],
  },
  {
    id: "misc",
    label: "Misc & experimental polls",
    description: "Everything that doesn’t fit elsewhere: experimental, draft, or uncategorized polls.",
    kind: "leaf",
  },
];
