const fs = require('fs');
const path = require('path');
const p = path.join(__dirname, '..', 'src', 'data', 'pollsRegistry.ts');
const raw = fs.readFileSync(p, 'utf8');
const ids = [];
const re = /id:\s*"([^"]+)"/g;
let m;
while ((m = re.exec(raw))) ids.push(m[1]);
const total = ids.length;
const autofill = ids.filter(id => /^autofill_/i.test(id));
const nonAuto = ids.filter(id => !/^autofill_/i.test(id));
console.log('registry total polls:', total);
console.log('autofill polls:', autofill.length);
console.log('non-autofill polls:', nonAuto.length);
console.log('sample non-autofill ids (first 20):', nonAuto.slice(0,20).join(', '));
